### ISSUE TITLE
Different mutation for empty hashes

### ISSUE THREAD

**Issue by jonathonjones** [txus/mutant#5]
Today, I got the following mutation:

```
Mutating line 5
  errors = {} >>> errors = {}
```

I see that the normal way you deal with hashes is to change the values for each of the keys, but of course empty hashes have no values and therefore nothing gets modified.

I have some ideas about ways of modifying the mutation, so I'll try to submit a pull request soon.

**Comment by txus** [comment]
Great! I'd love to hear your ideas. Actually I'm not sure about how would be a useful mutation of an empty hash, so let's see :)

**Comment by jonathonjones** [comment]
One way would just be to add a random extra thing to the hash, so that it becomes {:something => "something else"}. That might be more complicated than necessary, though. The easiest thing would be to just skip modifying a hash if the hash is empty.

**Comment by txus** [comment]
Closing this since the PR was merged.
